package motorph_GUI;

import motorph_GUI.ForgotPasswordForm;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import data_reader9.EmployeeDetailsReader;
import data_reader9.LeaveRequestReader;
import motorph9.EmployeeUser;
import motorph9.EmployeeUserDataManager;
import motorph9.FinanceUser;
import motorph9.HRUser;
import motorph9.ITUser;
import motorph9.User;

public class Login extends javax.swing.JFrame {

    private static final String CSV_FILE = "src/data9/Login.csv";
    private JTextField usernameField;
    private JPasswordField passwordField;
    private JButton loginButton;
    private EmployeeDetailsReader employeeReader;
    private EmployeeUserDataManager employeeDataManager = new EmployeeUserDataManager();

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setResizable(false); // 💡 Prevent resizing
        this.setExtendedState(JFrame.NORMAL);
        setMinimumSize(new java.awt.Dimension(957, 490)); 
        pack();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        employeeReader = new EmployeeDetailsReader("src/data9/Employee.csv", "src/data9/Login.csv");
        //reader = new EmployeeDetailsReader();
        jBtnLogin.addActionListener(new LoginActionListener());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlBlack = new javax.swing.JPanel();
        jLblForgotPassword = new javax.swing.JLabel();
        jUsernameField = new javax.swing.JTextField();
        jPwordField = new javax.swing.JPasswordField();
        jBtnLogin = new javax.swing.JButton();
        jLblPword = new javax.swing.JLabel();
        jLabelMotor = new javax.swing.JLabel();
        jLabelPH = new javax.swing.JLabel();
        jLblUname = new javax.swing.JLabel();
        LOGO1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jPnlBlack.setBackground(new java.awt.Color(255, 255, 255));
        jPnlBlack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLblForgotPassword.setBackground(new java.awt.Color(0, 0, 102));
        jLblForgotPassword.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLblForgotPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLblForgotPassword.setText("<html><u>Forgot Password</u></html>");
        jLblForgotPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLblForgotPasswordMouseClicked(evt);
            }
        });
        jPnlBlack.add(jLblForgotPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 100, 40));

        jUsernameField.setBackground(new java.awt.Color(215, 235, 255));
        jUsernameField.setFont(jUsernameField.getFont());
        jUsernameField.setToolTipText("Enter username");
        jUsernameField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jUsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsernameFieldActionPerformed(evt);
            }
        });
        jPnlBlack.add(jUsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 200, 30));

        jPwordField.setBackground(new java.awt.Color(215, 235, 255));
        jPwordField.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jPwordField.setToolTipText("Enter password");
        jPwordField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPnlBlack.add(jPwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 200, 30));

        jBtnLogin.setBackground(new java.awt.Color(153, 204, 255));
        jBtnLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnLogin.setForeground(new java.awt.Color(0, 51, 102));
        jBtnLogin.setText("LOGIN");
        jBtnLogin.setBorder(null);
        jBtnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnLoginMousePressed(evt);
            }
        });
        jBtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLoginActionPerformed(evt);
            }
        });
        jPnlBlack.add(jBtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 130, 30));

        jLblPword.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLblPword.setForeground(new java.awt.Color(0, 51, 102));
        jLblPword.setText("Password");
        jPnlBlack.add(jLblPword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, 50));

        jLabelMotor.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMotor.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabelMotor.setText("MOTOR");
        jPnlBlack.add(jLabelMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 150, 60));

        jLabelPH.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabelPH.setForeground(new java.awt.Color(0, 51, 153));
        jLabelPH.setText("PH");
        jPnlBlack.add(jLabelPH, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 70, 100));

        jLblUname.setBackground(new java.awt.Color(0, 0, 102));
        jLblUname.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLblUname.setForeground(new java.awt.Color(0, 51, 102));
        jLblUname.setText("Username");
        jPnlBlack.add(jLblUname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 80, 30));

        LOGO1.setBackground(new java.awt.Color(0, 0, 102));
        LOGO1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        LOGO1.setForeground(new java.awt.Color(255, 255, 255));
        LOGO1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/LogoMotorPH(small).png"))); // NOI18N
        LOGO1.setText("Username");
        jPnlBlack.add(LOGO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 100, 100));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/MotorPH BG.png"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(500, 434));
        jPnlBlack.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 680, 420));

        getContentPane().add(jPnlBlack);
        jPnlBlack.setBounds(0, 0, 960, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private class LoginActionListener implements ActionListener {
            @Override
    public void actionPerformed(ActionEvent e) {
        String username = jUsernameField.getText();
        String password = new String(jPwordField.getPassword());

        User user = validateLogin(username, password);
        if (user == null) {
            JOptionPane.showMessageDialog(Login.this, "Incorrect Credentials.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(Login.this, "Login Successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
            openDashboard(user); // ✅ Calls method to open the dashboard
            dispose(); // ✅ Closes login window
        }
    }

    private User validateLogin(String username, String password) {
        employeeReader = new EmployeeDetailsReader("src/data9/Employee.csv", "src/data9/Login.csv");
        //User user = employeeReader.getLoginDetails(username); // ✅ Fetch user by username
        User user = employeeDataManager.getUser(username);

        if (user != null) {
            System.out.println("Loaded user: " + user.getUsername() + ", Password: " + user.getPassword());

            if (user.getPassword().equals(password)) { // ✅ Check if password matches
                return user;
            }
        }

        System.out.println("❌ Login failed for user: " + username);
        return null;
    }

    private void openDashboard(User user) {
        employeeReader = new EmployeeDetailsReader("src/data9/Employee.csv", "src/data9/Login.csv");
        LeaveRequestReader leaveRequestReader = new LeaveRequestReader();

        // ✅ Ask user to change the default password
        if (user.getChangePassword().equalsIgnoreCase("YES")) {
            String newPassword;

            while (true) {
                newPassword = JOptionPane.showInputDialog(Login.this, 
                    "Enter a new password:", 
                    "Change Password Required", JOptionPane.WARNING_MESSAGE);

                // If user clicks Cancel or closes the dialog, relaunch the login page
                if (newPassword == null) {
                    JOptionPane.showMessageDialog(Login.this, 
                        "Returning to login.", 
                        "Password change cancelled", JOptionPane.WARNING_MESSAGE);

                    // Close the current login window
                    Login.this.dispose();

                    // Relaunch the login page
                    Login newClassInstance = new Login();
                    newClassInstance.setVisible(true);
                    return;
                }

                // Trim and validate password
                if (!newPassword.trim().isEmpty()) {
                    employeeReader.changeUserPassword(user.getEmployeeId(), newPassword);
                    JOptionPane.showMessageDialog(Login.this, 
                        "✅ Password successfully changed!", 
                        "Success", JOptionPane.INFORMATION_MESSAGE);
                    break;
                } else {
                    JOptionPane.showMessageDialog(Login.this, 
                        "❌ Password change is required to continue.", 
                        "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }

        // ✅ Open the correct dashboard based on user type
        if (user instanceof HRUser) {
            HRDashboard hrDashboard = new HRDashboard((HRUser) user, employeeReader, leaveRequestReader);
            hrDashboard.setVisible(true);
        } else if (user instanceof ITUser) {
            ITDashboard itDashboard = new ITDashboard((ITUser) user);
            itDashboard.setVisible(true);
        } else if (user instanceof FinanceUser) {
            FinanceDashboard financeDashboard = new FinanceDashboard((FinanceUser) user);
            financeDashboard.setVisible(true);
        } else if (user instanceof EmployeeUser) {
            EmployeeDashboard employeeDashboard = new EmployeeDashboard((EmployeeUser) user);
            employeeDashboard.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(Login.this, "Unknown user type. Cannot open dashboard.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

}
    
  
    private void jBtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLoginActionPerformed

    }//GEN-LAST:event_jBtnLoginActionPerformed

    private void jBtnLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLoginMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnLoginMousePressed

    private void jLblForgotPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblForgotPasswordMouseClicked
// Open the Forgot Password Form when clicked
        ForgotPasswordForm form = new ForgotPasswordForm();
        form.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLblForgotPasswordMouseClicked

    private void jUsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUsernameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        SwingUtilities.invokeLater(() -> {
            Login login = new Login();
            login.setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOGO1;
    private javax.swing.JButton jBtnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMotor;
    private javax.swing.JLabel jLabelPH;
    private javax.swing.JLabel jLblForgotPassword;
    private javax.swing.JLabel jLblPword;
    private javax.swing.JLabel jLblUname;
    private javax.swing.JPanel jPnlBlack;
    private javax.swing.JPasswordField jPwordField;
    private javax.swing.JTextField jUsernameField;
    // End of variables declaration//GEN-END:variables
}
